### ISSUE TITLE
Подключить liquibase

### ISSUE THREAD

**Issue by AlexBugrimov** [Mr-Anonim-377/Sales#11]
Добавить liquibase в проект для удобства работы с миграциями и версионностью БД.
[liquibase](http://www.liquibase.org/documentation/index.html)
Можно другие варианты работы с БД и миграциями

**Comment by AlexBugrimov** [comment]
Реализовать раньше чем контроллеры. Подними приоритет

**Comment by Mr-Anonim-377** [comment]
подключил FlyWay, создал пару миграций
