### ISSUE TITLE
Сверстать главную страницу интернет магазина 

### ISSUE THREAD

**Issue by Mr-Anonim-377** [Mr-Anonim-377/Sales#22]
Сверстать главную страницу интернет магазина  в соответствии с дизайном в Figma

**Comment by AlexBugrimov** [comment]
Почитайте пожалуйста [БЭМ](https://ru.bem.info/methodology/css/)
Я думаю это поможет вам прийти к какому-то единому стилю верстки.

**Comment by AlexBugrimov** [comment]
Слишком большая задача. Разбейте на подзадачи. Будет легче
* [ ] Реализовать Header
* [ ] Реализовать контентную часть
* [ ] Реализовать Footer

Можно еще мельче)))

**Comment by AlexBugrimov** [comment]
![image](https://user-images.githubusercontent.com/30559567/67264006-7f621080-f4b2-11e9-8500-527798d97e6f.png)

О боги. По ссылке на FIGMA - 404

**Comment by Mr-Anonim-377** [comment]
Решена проблема с фигмой

**Comment by Mr-Anonim-377** [comment]
раздробил задачи, буду планировать лучше!
