### ISSUE TITLE
md для базы данных 

### ISSUE THREAD

**Issue by Mr-Anonim-377** [Mr-Anonim-377/Sales#25]
Создать мд для базы данных и положить ссылку в главный мд

**Comment by AlexBugrimov** [comment]
**А чего label не повесил?**

**Comment by AlexBugrimov** [comment]
**И в спринт не включил?**

**Comment by Mr-Anonim-377** [comment]
Не успел еще, сейчас включу

**Comment by Mr-Anonim-377** [comment]
Включил-нашел как это делать.
