### ISSUE TITLE
Добавить модель Image и связать ее с Sales

### ISSUE THREAD

**Issue by AlexBugrimov** [Mr-Anonim-377/Sales#4]

**Comment by AlexBugrimov** [comment]
А вообще это нужно? хранить одну картинку в отдельной таблице. Она же одна. Ну и пусть будет полем в Sales

**Comment by Mr-Anonim-377** [comment]
Соглашусь, так удаться избавиться от лишних связей

**Comment by Mr-Anonim-377** [comment]
Но сделаю это позже, пока обновил bigInt на uuid и создал сущности
